
package pharmacymanagmentsystem;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

public class AddCustomerPanel extends javax.swing.JPanel {

 private Customer_Manager customerManager;
private AddNewSalePanel addPanel ;
     private JTextField idField;
    private JTextField nameField;
    private JTextField contactField;
    public AddCustomerPanel(Customer_Manager customerManager,AddNewSalePanel addPanel ) {
        this.customerManager = customerManager;
        this.addPanel=addPanel;
 

              
        setLayout(new GridLayout(5, 2, 10, 10)); // 🧱 Simple layout

        // 🔢 ID Field (Auto-generated)
        idField = new JTextField();
        idField.setEditable(false); // Auto-generated
        refreshCustomerID(); // Set new ID

        nameField = new JTextField();
        contactField = new JTextField();
        JButton addBtn = new JButton("Add Customer");

        // 👁️‍🗨️ Layout
        add(new JLabel("Customer ID (Auto):"));
        add(idField);
        add(new JLabel("Name:"));
        add(nameField);
        add(new JLabel("Contact No.:"));
        add(contactField);
        add(new JLabel()); // Empty filler
        add(addBtn);

        // ➕ Add Button Logic
        addBtn.addActionListener(e -> {
            String id = idField.getText().trim();
            String name = nameField.getText().trim();
            String contact = contactField.getText().trim();

            if (name.isEmpty() || contact.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields.", "Input Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            boolean success = customerManager.addCustomerToDatabase(id, name, contact);
            if (success) {
                JOptionPane.showMessageDialog(this, "✅ Customer added successfully!");

                // 🧹 Reset fields
                refreshCustomerID(); // get new unique ID
                nameField.setText("");
                contactField.setText("");
                 addPanel.refreshCustomerDropdown();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Failed to add customer. Try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    // 🔄 Refresh ID from DB (avoid duplicate)
    private void refreshCustomerID() {
        String newID = customerManager.generateCustomerID();
        idField.setText(newID);
    }

    public AddCustomerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
