/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pharmacymanagmentsystem;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.util.List;


public class CustomerManagerPanel extends javax.swing.JPanel {
private CardLayout cardLayout;
//    private JPanel contentPanel;
//    public CustomerManagerPanel(Customer_Manager customerManager,AddNewSalePanel addPanel ) {
//        
//        setLayout(new BorderLayout());
//
//        JTabbedPane customerTabs = new JTabbedPane();
//        customerTabs.addTab("Add", new AddCustomerPanel(customerManager));
//        customerTabs.addTab("Update", new UpdateCustomerPanel(customerManager));
//        customerTabs.addTab("Delete", new DeleteCustomerPanel(customerManager));
//        customerTabs.addTab("All", new ViewAllCustomersPanel(customerManager));
//
//        add(customerTabs, BorderLayout.CENTER);
//    }


    private JPanel contentPanel;

    public CustomerManagerPanel(Customer_Manager customerManager, AddNewSalePanel addPanel) {

        setLayout(new BorderLayout());

        JTabbedPane customerTabs = new JTabbedPane();

        // 👉 Forward the shared AddNewSalePanel to AddCustomerPanel
        customerTabs.addTab("Add", new AddCustomerPanel(customerManager, addPanel));
        customerTabs.addTab("Update", new UpdateCustomerPanel(customerManager));
        customerTabs.addTab("Delete", new DeleteCustomerPanel(customerManager));
        customerTabs.addTab("All", new ViewAllCustomersPanel(customerManager));

        add(customerTabs, BorderLayout.CENTER);
    }

    public CustomerManagerPanel() {
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
