/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pharmacymanagmentsystem;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import pharmacymanagmentsystem.DBConnection;
/**
 *
 * @author HP
 */
public class DeleteSupplierPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteSupplierPanel
     */
    public DeleteSupplierPanel(Supplier_Manager supplierManager) {
        initializeComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   
   private void initializeComponents() {
       // Set layout: 3 rows, 2 columns, with padding
       setLayout(new GridLayout(3, 2, 10, 10));
 
       // --- GUI Components ---
       JLabel supplierIDLabel = new JLabel("Supplier ID to Delete:");
       JTextField supplierIDField = new JTextField(20);
       JButton deleteBtn = new JButton("Delete Supplier");
 
       // --- Add Components to Panel ---
       add(supplierIDLabel);
       add(supplierIDField);
       add(new JLabel()); // Empty cell
       add(deleteBtn);
       add(new JLabel()); // Optional spacing
       add(new JLabel()); // Optional spacing
 
       // --- Delete Button Logic ---
       deleteBtn.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               String supplierIdToDelete = supplierIDField.getText().trim();
 
               // Validate input
               if (supplierIdToDelete.isEmpty()) {
                   JOptionPane.showMessageDialog(DeleteSupplierPanel.this,
                           "Please enter the Supplier ID to delete.",
                           "Input Required",
                           JOptionPane.WARNING_MESSAGE);
                   return;
               }
 
               Connection conn = null;
               PreparedStatement pstmt = null;
 
               try {
                   conn = DBConnection.getConnection();
                   String sql = "DELETE FROM suppliers WHERE supplier_id = ?";
                   pstmt = conn.prepareStatement(sql);
                   pstmt.setString(1, supplierIdToDelete);
 
                   int rowsAffected = pstmt.executeUpdate();
 
                   if (rowsAffected > 0) {
                       JOptionPane.showMessageDialog(DeleteSupplierPanel.this,
                               "Supplier with ID '" + supplierIdToDelete + "' deleted successfully!",
                               "Success",
                               JOptionPane.INFORMATION_MESSAGE);
                       supplierIDField.setText(""); // Clear field
                   } else {
                       JOptionPane.showMessageDialog(DeleteSupplierPanel.this,
                               "No supplier found with ID '" + supplierIdToDelete + "'.",
                               "Not Found",
                               JOptionPane.WARNING_MESSAGE);
                   }
 
               } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(DeleteSupplierPanel.this,
                           "Database Error: " + ex.getMessage(),
                           "Error",
                           JOptionPane.ERROR_MESSAGE);
                   ex.printStackTrace();
               } catch (Exception ex) {
                   JOptionPane.showMessageDialog(DeleteSupplierPanel.this,
                           "Unexpected Error: " + ex.getMessage(),
                           "Error",
                           JOptionPane.ERROR_MESSAGE);
                   ex.printStackTrace();
               } finally {
                   try {
                       if (pstmt != null) pstmt.close();
                       if (conn != null) conn.close();
                   } catch (SQLException closeEx) {
                       JOptionPane.showMessageDialog(DeleteSupplierPanel.this,
                               "Error closing DB resources: " + closeEx.getMessage(),
                               "Resource Close Error",
                               JOptionPane.ERROR_MESSAGE);
                       closeEx.printStackTrace();
                   }
               }
           }
       });
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
