/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pharmacymanagmentsystem;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author mapple.pk
 */
public class MedicineManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineManagerPanel
     */
    public MedicineManagerPanel() {
        initComponents();
    }

    private CardLayout cardLayout;
    private JPanel contentPanel;
    private AddMedicinePanel addMedicinePanel;

    private MedicineManager medicineManager;
    private Manufacturer_Manager manufacturerManager;

    public MedicineManagerPanel(MedicineManager manager, Manufacturer_Manager manufacturerManager, AddMedicinePanel addMedicinePanel) {
        this.medicineManager = manager;
        this.manufacturerManager = manufacturerManager;
        this.addMedicinePanel = addMedicinePanel;
        setLayout(new BorderLayout());

        // Top Menu Buttons
        JPanel buttonPanel = new JPanel();
        JButton addBtn = new JButton("Add Medicine");
        JButton viewBtn = new JButton("View All");
        JButton updateBtn = new JButton("Update Stock");
        JButton deleteBtn = new JButton("Delete Medicine");
        JButton expiredBtn = new JButton("Check Expired");
        JButton reorderBtn = new JButton("Reorder Status");
        JButton searchBtn = new JButton("Search Medicine");

        buttonPanel.add(addBtn);
        buttonPanel.add(viewBtn);
        buttonPanel.add(updateBtn);
        buttonPanel.add(deleteBtn);
        buttonPanel.add(expiredBtn);
        buttonPanel.add(reorderBtn);
        buttonPanel.add(searchBtn);

        // Center Card Panel
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

//        contentPanel.add(new AddMedicinePanel(medicineManager,manufacturerManager), "ADD");
        contentPanel.add(addMedicinePanel, "ADD");

        contentPanel.add(new ViewMedicinePanel(medicineManager), "VIEW");
        contentPanel.add(new UpdateMedicinePanel(medicineManager), "UPDATE");
        contentPanel.add(new DeleteMedicinePanel(medicineManager), "DELETE");
        contentPanel.add(new ExpiredMedicinePanel(medicineManager), "EXPIRED");
        contentPanel.add(new ReorderStatusPanel(medicineManager), "REORDER");
        contentPanel.add(new SearchMedicinePanel(medicineManager), "SEARCH");

        // Action Listeners for Navigation
        addBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "ADD"));
        viewBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "VIEW"));
        updateBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "UPDATE"));
        deleteBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "DELETE"));
        expiredBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "EXPIRED"));
        reorderBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "REORDER"));
        searchBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "SEARCH"));

        // Add components
        add(buttonPanel, BorderLayout.NORTH);
        add(contentPanel, BorderLayout.CENTER);
    }

    // You will create each inner panel class in its own file:
    // AddMedicinePanel, ViewAllPanel, UpdateMedicinePanel, etc.
    // All of them will use medicineManager methods to perform backend logic
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
