package pharmacymanagmentsystem;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class OrderManagerPanel extends JPanel {

     private CardLayout cardLayout;
    private JPanel contentPanel;

    public OrderManagerPanel(Order_Manager orderManager, MedicineManager medicineManager, Supplier_Manager supplierManager,Manufacturer_Manager manufacturerManager) {
        setLayout(new BorderLayout());

        // ✅ Load medicines only once from database
        medicineManager.getAllMedicinesFromDatabase();

        // --- Top Button Panel ---
        JPanel buttonPanel = new JPanel();
        JButton addBtn = new JButton("Add Order");
        JButton viewBtn = new JButton("View All Orders");
        JButton updateBtn = new JButton("Update Order");
        JButton deleteBtn = new JButton("Delete Order");
        JButton searchBtn = new JButton("Search Order");

        buttonPanel.add(addBtn);
        buttonPanel.add(viewBtn);
        buttonPanel.add(updateBtn);
        buttonPanel.add(deleteBtn);
        buttonPanel.add(searchBtn);

        // --- Center Content Area (using CardLayout) ---
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

        // ✅ Pass the same manager objects to all panels
        AddOrderPanel addOrderPanel = new AddOrderPanel(orderManager, medicineManager, supplierManager, manufacturerManager);
        ViewAllOrdersPanel viewPanel = new ViewAllOrdersPanel(orderManager, medicineManager, supplierManager,manufacturerManager);
        UpdateOrderPanel updatePanel = new UpdateOrderPanel(orderManager, medicineManager, supplierManager,manufacturerManager);
        DeleteOrderPanel deletePanel = new DeleteOrderPanel(orderManager);
        SearchOrderPanel searchPanel = new SearchOrderPanel(orderManager,manufacturerManager);
        contentPanel.add(addOrderPanel, "ADD");
        contentPanel.add(viewPanel, "VIEW");
        contentPanel.add(updatePanel, "UPDATE");
        contentPanel.add(deletePanel, "DELETE");
        contentPanel.add(searchPanel, "SEARCH");

        // --- Button Actions ---
        addBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "ADD"));
        viewBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "VIEW"));
        updateBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "UPDATE"));
        deleteBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "DELETE"));
        searchBtn.addActionListener((ActionEvent e) -> cardLayout.show(contentPanel, "SEARCH"));

        // --- Add to layout ---
        add(buttonPanel, BorderLayout.NORTH);
        add(contentPanel, BorderLayout.CENTER);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
