/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pharmacymanagmentsystem;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import pharmacymanagmentsystem.DBConnection;
 
/**
 *
 * @author HP
 */
public class SearchSupplierPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchSupplierPanel
     */
       public SearchSupplierPanel() {
       initComponents();
   }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
public SearchSupplierPanel(Supplier_Manager manager) {
       setLayout(new GridLayout(5, 2, 10, 10));
 
       JTextField supplierIDField = new JTextField();
       JLabel nameLabel = new JLabel("Name: ");
       JLabel companyLabel = new JLabel("Company: ");
       JLabel contactLabel = new JLabel("Contact: ");
       JButton searchBtn = new JButton("Search Supplier");
 
       add(new JLabel("Supplier ID:"));
       add(supplierIDField);
       add(new JLabel("Name:"));
       add(nameLabel);
       add(new JLabel("Company:"));
       add(companyLabel);
       add(new JLabel("Contact:"));
       add(contactLabel);
       add(new JLabel());
       add(searchBtn);
 
       searchBtn.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               String id = supplierIDField.getText().trim();
               if (id.isEmpty()) {
                   JOptionPane.showMessageDialog(SearchSupplierPanel.this, "Please enter Supplier ID.");
                   return;
               }
 
               try (Connection conn = DBConnection.getConnection()) {
                   String sql = "SELECT name, company, contact FROM suppliers WHERE supplier_id = ?";
                   try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                       pstmt.setString(1, id);
                       try (ResultSet rs = pstmt.executeQuery()) {
                           if (rs.next()) {
                               nameLabel.setText("Name: " + rs.getString("name"));
                               companyLabel.setText("Company: " + rs.getString("company"));
                               contactLabel.setText("Contact: " + rs.getString("contact"));
                           } else {
                               JOptionPane.showMessageDialog(SearchSupplierPanel.this, "Supplier not found.");
                               nameLabel.setText("Name: ");
                               companyLabel.setText("Company: ");
                               contactLabel.setText("Contact: ");
                           }
                       }
                   }
               } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(SearchSupplierPanel.this, "Database error: " + ex.getMessage());
                   ex.printStackTrace();
               }
           }
       });
   }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
