/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pharmacymanagmentsystem;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*; 

public class ViewAllCustomersPanel extends javax.swing.JPanel {

    private Customer_Manager customerManager;
    private JTable customerTable;
    private DefaultTableModel model;
    private JComboBox<String> searchTypeBox;
    private JTextField searchField;

   public ViewAllCustomersPanel(Customer_Manager customerManager) {
        this.customerManager = customerManager;
        setLayout(new BorderLayout(10, 10));

        // 🔍 Top Search Panel
        JPanel searchPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        searchTypeBox = new JComboBox<>(new String[]{"Customer ID", "Customer Name"});
        searchField = new JTextField(15);
        JButton searchBtn = new JButton("🔍 Search");
        JButton refreshBtn = new JButton("🔁 Refresh");

        searchPanel.add(new JLabel("Search by:"));
        searchPanel.add(searchTypeBox);
        searchPanel.add(searchField);
        searchPanel.add(searchBtn);
        searchPanel.add(refreshBtn);

        // 📋 Table setup
        String[] columns = {"Customer ID", "Name", "Contact No"};
        model = new DefaultTableModel(columns, 0);
        customerTable = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(customerTable);

        // 👉 Add to layout
        add(searchPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);

        // 🔁 Load all initially
        loadAllCustomers();  // Important call here

        // 🔍 Search functionality
        searchBtn.addActionListener(e -> searchCustomer());

        // 🔄 Refresh functionality
        refreshBtn.addActionListener(e -> {
            searchField.setText("");
            loadAllCustomers();  // Re-fetch fresh from DB
        });
    }

    // ✅ Fix: Always load latest customers from DB
    private void loadAllCustomers() {
        customerManager.loadCustomersFromDatabase(); // ✨ Important!
        model.setRowCount(0); // Clear old table data

        for (Customer c : customerManager.getCustomerList()) {
            model.addRow(new Object[]{c.getCustomerID(), c.getName(), c.getContactNumber()});
        }
    }

    private void searchCustomer() {
        String searchBy = (String) searchTypeBox.getSelectedItem();
        String keyword = searchField.getText().trim().toLowerCase();

        model.setRowCount(0); // Clear table

        for (Customer c : customerManager.getCustomerList()) {
            if (searchBy.equals("Customer ID") && c.getCustomerID().toLowerCase().contains(keyword)) {
                model.addRow(new Object[]{c.getCustomerID(), c.getName(), c.getContactNumber()});
            } else if (searchBy.equals("Customer Name") && c.getName().toLowerCase().contains(keyword)) {
                model.addRow(new Object[]{c.getCustomerID(), c.getName(), c.getContactNumber()});
            }
        }
    }

    // Constructor for GUI Editor compatibility
public ViewAllCustomersPanel() {
        initComponents();
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
